apiVersion: v1
kind: Service
metadata:
  name: dotnetapi
  namespace: dotnetapi
  labels:
    app: dotnetapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: dotnetapi
